# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
os: linux
dist: xenial

after_success:
  - Rscript -e 'covr::codecov()'

jobs:
  include:
  - r: release
#    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
    before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: devel
