on:
  push:
    branches:
      - release
      - master
      - devel

  pull_request:
    branches:
      - master

name: Test coverage

jobs:
  test-coverage:
    runs-on: macOS-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Query dependencies
        shell: Rscript {0}
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          install.packages(c("remotes", "devtools"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")

      - name: Roxygenize
        shell: Rscript {0}
        run: |
          # Vignettes are not needed for coverage tests
          devtools::document(roclets = c('rd', 'collate', 'namespace'))

      - name: Test coverage
        shell: Rscript {0}
        run:   covr::codecov()
